name: Update readme development stats

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-16.04
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
